apiVersion: v1
kind: Service
metadata:
  name: { { include "pgpool-operator.fullname" . } }
  labels:
    { { - include "pgpool-operator.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: http
      protocol: TCP
      name: http
  selector:
    { { - include "pgpool-operator.selectorLabels" . | nindent 4 } }
