apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgpools.pgpool-operator.jfsanchez.net
spec:
  group: pgpool-operator.jfsanchez.net
  names:
    kind: PgPool
    singular: pgpool
    plural: pgpools
    shortNames:
      - pgp
    categories:
      - all
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: ClusterName
          jsonPath: .spec.clusterName
          type: string
      schema:
        openAPIV3Schema:
          type: object
          required:
            - kind
            - apiVersion
            - spec
          properties:
            kind:
              type: string
              enum:
                - PgPool
            apiVersion:
              type: string
              enum:
                - pgpool-operator.jfsanchez.net/v1
            spec:
              type: object
              required:
                - clusterName
              properties:
                pgPoolImage:
                  type: string
                clusterName:
                  type: string
                port:
                  type: integer
                maxPoolSize:
                  type: integer
                numInitChildren:
                  type: integer
                healthCheckPeriod:
                  type: integer
                childLifeTime:
                  type: integer
                childMaxConnections:
                  type: integer
                connectionLifeTime:
                  type: integer
                clientIdleLimit:
                  type: integer
                connectionCache:
                  type: boolean
                loadBalanceMode:
                  type: boolean
                ssl:
                  type: boolean
                failoverOnBackendError:
                  type: boolean
